debian: Cleanup debianization
RevolutionPi/revpi-modbus pull request #41
Opened 2023-01-13 15:19 UTC by iluminat23

* remove dh-exec build dependecy
* update debhelper to 12 (Debian Buster)
* update Standards-Version to 4.3.0 (debhelper 12/Debian Buster)
* change Homepage to https://revolutionpi.com/
* add Vcs-Browser/Vcs-Git
* clean up and simplify rules file
* add min. libmodbus version (3.16) to the dependency
* Set: Rules-Requires-Root: no

Signed-off-by: Philipp Rosenberger <p.rosenberger@kunbus.com>

2023-01-16 10:12 UTC, naruxde requested changes

2023-01-16 10:12 UTC, naruxde commented on debian/rules
> -override_dh_systemd_enable:
We need this line, the piControl will enable this, if we configure virtual modes devices in piCtory

2023-01-17 22:41 UTC, RamiGspo reviewed
In the commit "c958983" you wrote "dependecy". It should be "dependency"

2023-01-18 08:19 UTC, naruxde approved these changes

2023-01-18 08:49 UTC, RamiGspo approved these changes

2023-01-19 08:52 UTC, closed without merging